version: "3"

services: 
  minecraft-server:
    build:
      context: .
      args:
        RAM_AMOUNT: ${RAM_AMOUNT}
    volumes:
      - .server:/server
    ports:
      - 25565:25565
    container_name: ${CONTAINER_NAME}
    
volumes:
  server:
